
server.port=8081
spring.application.name=my-first-java-app
spring.datasource.url=jdbc:postgresql://localhost:5432/student_db
spring.datasource.username=ritesh
spring.datasource.password=ritesh63
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true